apiVersion: app.stacks/v1beta1
kind: RuntimeComponent
metadata:
  labels:
    image.opencontainers.org/title: sample-service-binding-postgresql
  name: sample-service-binding-postgresql
spec:
  applicationImage: harishyayi/sample-service-binding-postgresql:2710
  createKnativeService: false
  expose: true
  service:
    annotations:
      prometheus.io/path: /actuator/prometheus
      prometheus.io/scrape: "true"
    port: 8080
    type: ClusterIP
  version: 1.0.0
  volumeMounts:
  - mountPath: /etc/secrets/postgres
    name: service-binding
    readOnly: true
  volumes:
  - name: service-binding
    secret:
      secretName: service-binding
#  bindings:
#    embedded:
#      apiVersion: operators.coreos.com/v1alpha1
#      kind: ServiceBinding
#      spec:
#        backingServiceSelector:
#          group: postgresql.dev
#          kind: Database
#          resourceRef: demo-database
#          version: v1alpha1
#        detectBindingResources: true
#        envVarPrefix: postgresql1
