apiVersion: operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name: postgres
spec:
  application:
    group: apps
    resource: deployments
    name: sample-service-binding-postgresql
    version: v1
  services:
  - group: postgresql.baiju.dev
    kind: Database
    name: demo-database
    version: v1alpha1
    id: postgresDB
  customEnvVar:
    - name: host
      value: '{{ .postgresDB.status.dbConnectionIP }}'
    - name: port
      value: '{{ .postgresDB.status.dbConnectionPort }}'
    - name: database
      value: '{{ .postgresDB.status.dbName}}'
    - name: username
      value: '{{ .postgresDB.status.dbCredentials.user }}'
    - name: password
      value: '{{ .postgresDB.status.dbCredentials.password }}'
    - name: type
      value: postgresql
  bindAsFiles: true