apiVersion: operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name: service-binding
spec:
  application:
    group: apps
    resource: deployments
    name: sample-service-binding-postgresql
    version: v1
  services:
  - group: postgresql.baiju.dev
    kind: Database
    name: demo-database
    version: v1alpha1
    id: postgresDB
  envVarPrefix: postgresql
  